# Generated by Django 3.1.3 on 2020-11-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Serie',
            new_name='serie',
        ),
    ]
