# Generated by Django 3.1.3 on 2020-11-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btg', '0002_auto_20201128_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='brne',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='lp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='obs',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='plle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='serie',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
