# Generated by Django 3.1.3 on 2020-11-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btg', '0004_auto_20201130_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='brne',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='lp',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='plle',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
