version: "3.3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
       - ${static_root}:/code/static
       - ${pwd_file}:/code/pwd.txt

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    ports:
      - 80:80

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
       - ${static_root}:/code/static
    ports:
      - 8000:80
    depends_on:
      - backend
