version: "3.3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    volumes:
       - "./backend/:/code/"
       - ${pwd_file}:/code/pwd.txt
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
      args:
        - REACT_APP_BACKEND_URL='http://localhost:8000/'
    volumes:
       - "./frontend/front-management-system/:/code/front-management-system/"
    stdin_open: true
    ports:
      - "3000:3000"
