version: "3.3"

services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
        - "5432:5432"
    volumes:
        - ${data_path}:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: houssemadouni11@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    volumes:
       - "./backend/:/code/"
    ports:
      - "8000:8000"
    environment:
      EPASS: ${EPASS}
    depends_on:
      - db
      # - pgadmin

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
      args:
        - REACT_APP_BACKEND_URL='http://localhost:8000/'
    volumes:
       - "./frontend/front-management-system/:/code/front-management-system/"
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    links:
      - backend
