version: "3.3"

services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
        - "5432:5432"
    volumes:
        - ${data_path}:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: houssemadouni11@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
       - ./static:/code/static
    environment:
      EPASS: ${EPASS}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    ports:
      - 80:80

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
       - ./static:/code/static
    ports:
      - 8000:80
    depends_on:
      - backend
