version: "3.3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    volumes:
       - "./backend/:/code/"
       - "/home/houssem/Bureau/pwd.txt:/code/pwd.txt"
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    volumes:
       - "./frontend/front-management-system/:/code/front-management-system/"
    stdin_open: true
    ports:
      - "3000:3000"
