version: "3.3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    volumes:
       - "./backend/:/code/"
       - "/home/ubuntu/houssem_v1/pwd.txt:/code/pwd.txt"
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    env_file:
      - prod.env
    stdin_open: true
    ports:
      - "3000:3000"
