# Generated by Django 3.1.3 on 2021-01-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20201127_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='route',
            field=models.CharField(blank=True, choices=[('calendar', 'calendar'), ('route', 'route')], max_length=300, null=True),
        ),
    ]
