FROM python:3.9
ENV PYTHONUNBUFFERED=1
RUN mkdir /code
COPY . /code/
RUN pip install -r /code/requirements.txt
WORKDIR /code/backend_managing_system
RUN chmod +x /code/start_command_dev.sh
CMD sh /code/start_command_dev.sh
