# Generated by Django 3.1.3 on 2020-11-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=True)),
                ('link', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='calendar',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
