# Generated by Django 3.1.3 on 2020-11-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_auto_20201109_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=5000)),
                ('email', models.EmailField(max_length=5000)),
                ('duree', models.CharField(max_length=5000)),
                ('tool', models.CharField(max_length=5000)),
                ('comment', models.CharField(max_length=5000)),
                ('crenau', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.calendar')),
                ('teams_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.teamlink')),
            ],
        ),
    ]
