# Generated by Django 3.1.3 on 2020-11-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_rdv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='teams_link',
            field=models.CharField(max_length=5000),
        ),
    ]
