# Generated by Django 3.1.3 on 2020-11-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_auto_20201111_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='teams_link',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
