# Generated by Django 3.1.3 on 2020-11-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_auto_20201111_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='teams_link',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
