# Generated by Django 3.1.3 on 2020-11-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_auto_20201111_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='comment',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
