# Generated by Django 3.1.3 on 2020-11-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0008_auto_20201113_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamlink',
            name='link',
            field=models.CharField(max_length=5000, unique=True),
        ),
    ]
