# Generated by Django 3.1.3 on 2020-11-24 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0009_auto_20201115_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='crenau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.calendar'),
        ),
    ]
