# Generated by Django 3.1.3 on 2020-11-27 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0010_auto_20201124_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdv',
            old_name='username',
            new_name='name',
        ),
    ]
