# Generated by Django 3.1.3 on 2020-12-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0011_auto_20201127_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='duree',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='email',
            field=models.EmailField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='name',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='teams_link',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='tool',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
