# Generated by Django 3.1.3 on 2020-12-02 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0012_auto_20201202_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='picked_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 23, 4, 4, 752278)),
        ),
    ]
