# Generated by Django 3.1.3 on 2020-12-03 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0013_rdv_picked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='picked_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 1, 11, 34, 544732)),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='teams_link',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
