# Generated by Django 3.1.3 on 2020-12-05 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0016_auto_20201205_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkypeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=True)),
                ('link', models.CharField(max_length=5000, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rdv',
            name='picked_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 7, 29, 52, 425035)),
        ),
    ]
