# Generated by Django 3.1.3 on 2020-12-06 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0019_auto_20201205_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='picked_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 1, 30, 32, 537615)),
        ),
    ]
