# Generated by Django 3.1.3 on 2020-12-11 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0020_auto_20201206_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='picked_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 13, 20, 15, 994884)),
        ),
    ]
