# Generated by Django 3.1.3 on 2021-01-06 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0023_auto_20201221_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='picked_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 16, 6, 39, 829495)),
        ),
    ]
