# Generated by Django 3.1.3 on 2021-01-07 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0024_auto_20210106_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='picked_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 14, 42, 34, 73786)),
        ),
    ]
