# Generated by Django 3.1.3 on 2021-01-09 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0025_auto_20210107_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='picked_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 18, 19, 58, 141783)),
        ),
    ]
