# Generated by Django 3.1.3 on 2021-01-10 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0027_auto_20210110_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='picked_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 19, 11, 0, 700013)),
        ),
    ]
