# Generated by Django 3.1.3 on 2021-01-23 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0030_auto_20210112_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='picked_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 13, 9, 20, 233723)),
        ),
    ]
