# Generated by Django 3.1.3 on 2021-01-23 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0031_auto_20210123_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='picked_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 15, 12, 51, 544864)),
        ),
    ]
