# Generated by Django 3.1.3 on 2021-02-16 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0041_auto_20210215_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='picked_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 21, 7, 1, 963690)),
        ),
    ]
