# Generated by Django 3.1.3 on 2021-02-17 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0042_auto_20210216_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='picked_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 17, 23, 9, 47, 20252)),
        ),
    ]
